# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports = [
    <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    (let nixos-hardware =
           builtins.fetchTarball
             https://github.com/NixOS/nixos-hardware/archive/master.tar.gz;
     in "${nixos-hardware}/lenovo/thinkpad/t480s")
  ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-label/nixos";
      fsType = "ext4";
      options = [ "noatime" ];
    };

    "/boot" = {
      device = "/dev/disk/by-label/boot";
      fsType = "vfat";
    };
  };
  swapDevices = [ { device = "/dev/disk/by-label/swap"; } ];

  nix.maxJobs = lib.mkDefault 8;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = true;

  services.fstrim.enable = true;

  nixpkgs.config.allowUnfree = true;
  hardware.bumblebee.enable = true;
  environment.systemPackages = with pkgs; [ linuxPackages.bbswitch];

  services.xserver = {
    enable = true;

    # Tearing fix
    videoDrivers = [ "intel" ];
    deviceSection = ''
      Option "TearFree" "true"
    '';

    # Enable touchpad support.
    libinput.enable = true;

    # Disable mouse acceleration
    config = ''
      Section "InputClass"
        Identifier "mouse accel"
        Driver "libinput"
        MatchIsPointer "on"
        Option "AccelProfile" "flat"
        Option "AccelSpeed" "0"
      EndSection
    '';
  };
}
